Repository Boehringer-Ingelheim/eslint-config, pull requests merged in 2025-01, with the labels that each got.

#65 feat(base): [typescript-eslint] update parserOptions to use projectService instead of project
  CHANGELOG.md
  README.md
  configs/base.js
  package-lock.json
  package.json
Labels: enhancement

#67 feat(deps): update dependencies
  .github/workflows/release.yml
  .nvmrc
  package-lock.json
  package.json
Labels: dependencies

#68 fix(scripts): [repair] use exact rimraf version to not use a local an…
  package.json
Labels: bug

#69 feat(shared-configurations): add next.js configuration
  CHANGELOG.md
  README.md
  configs/nextjs.js
  configs/react.js
  index.js
  package-lock.json
  package.json
Labels: enhancement

#72 fix(react): [sort-jsx-props] use regex pattern for custom groups
  configs/react.js
Labels: bug

#71 feat(deps): update dependencies
  package-lock.json
  package.json
Labels: dependencies

#73 docs: document known issue with differentiating scopes of eslint and tsconfig
  README.md
Labels: documentation

#79 Release v7 (flat config)
  .eslintrc.js
  .github/workflows/release.yml
  .nvmrc
  .releaserc.js
  CHANGELOG.md
  README.md
  base/index.js
  base/local.js
  configs/base.js
  configs/experimental-naming-convention.js
  configs/local.js
  configs/nextjs.js
  configs/playwright.js
  configs/prettier-disable.js
  configs/react.js
  configs/strict.js
  eslint.config.mjs
  index.d.ts
  index.js
  package-lock.json
  package.json
  playwright/index.js
  prettier-disable/index.js
  react/index.js
Labels: enhancement, released on @next
